tests:
  ramp_up:
    intervals: # msg/s, duration in seconds
      - [ 1, 30 ]
      - [ 10, 30 ]
      - [ 50, 30 ]
      - [ 100, 30 ]
      - [ 150, 30 ]
      - [ 200, 30 ]

  burst:
    normal_rate:
      data_rate: 20  # msg/s
      interval_length: 10  # seconds
    burst_rate:
      data_rate: 10000  # msg/s
      interval_length: 2  # seconds
    number_of_repetitions: 3

  maximum_throughput:
    length: 60  # seconds

  long_term:
    data_rate: 15  # msg/s
    length: 10  # minutes

test_runs:
  - ramp_up
  - maximum_throughput
  - burst
  - long_term

environment:
  kafka_brokers:
    - hostname: 127.0.0.1
      port: 8097
    - hostname: 127.0.0.1
      port: 8098
    - hostname: 127.0.0.1
      port: 8099
  kafka_topics:
    pipeline:
      logserver_in: "pipeline-logserver_in"
  monitoring:
    clickhouse_server:
      hostname: clickhouse-server

logging:
  base:
    debug: false
  modules:
    controller.benchmark_controller:
      debug: false
    test_runner.benchmark_test_runner:
      debug: false
    test_runner.plotting.plot_generator:
      debug: false
    test_runner.test_types:
      debug: false

remote_execution:
  enabled: false
  host: "benchmark-vm" # Example: user@192.168.1.100
  key_path: "~/.ssh/id_ed25519"
