services:
  benchmark_test_runner:
    container_name: benchmark_test_runner
    build:
      context: ..
      dockerfile: src/Dockerfile
      network: host
    networks:
      - docker_heidgaf

networks:
  docker_heidgaf:
    external: true
